import { Card, MenuItems } from '../interface/page.interface';

export const mockCards: Card[] = [
  {
    id: '14',
    title: 'Разработка нового компонента для отображения графиков',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 100,
    status: 'inProgress',
    time: '5ч',
    assigned: true,
    product: 'option1',
    type: 'development',
  },
  {
    id: '15',
    title: 'Рефакторинг кода модуля авторизации',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 100,
    status: 'inProgress',
    time: '24ч',
    assigned: true,
    product: 'option2',
    type: 'test',
  },
  {
    id: '16',
    title: 'Тестирование новых компонентов',
    author: 'Михаил К.',
    avatarUrl: '/assets/img/person.png',
    progress: 90,
    status: 'inReview',
    time: '8ч',
    assigned: false,
    product: 'option1',
    type: 'test',
  },
  {
    id: '17',
    title: 'Оптимизация кода для уменьшения задержек',
    author: 'Екатерина Н.',
    avatarUrl: '/assets/img/person.png',
    progress: 75,
    status: 'inProgress',
    time: '12ч',
    assigned: true,
    product: 'option3',
    type: 'optimization',
  },
  {
    id: '18',
    title: 'Исправление ошибок рендеринга на мобильных устройствах',
    author: 'Дмитрий С.',
    avatarUrl: '/assets/img/person.png',
    progress: 50,
    status: 'inProgress',
    time: '30ч',
    assigned: false,
    product: 'allProducts',
    type: 'errors',
  },
  {
    id: '19',
    title: 'Сборка новой версии приложения',
    author: 'Анна М.',
    avatarUrl: '/assets/img/person.png',
    progress: 0,
    status: 'inProgress',
    time: '5ч',
    assigned: false,
    product: 'option2',
    type: 'deployment',
  },
  {
    id: '20',
    title: 'Создание макета нового интерфейса',
    author: 'Петр В.',
    avatarUrl: '/assets/img/person.png',
    progress: 65,
    status: 'inProgress',
    time: '15ч',
    assigned: true,
    product: 'option1',
    type: 'design',
  },
  {
    id: '21',
    title: 'Обновление базы данных для новой архитектуры',
    author: 'Сергей Т.',
    avatarUrl: '/assets/img/person.png',
    progress: 80,
    status: 'inProgress',
    time: '20ч',
    assigned: true,
    product: 'option3',
    type: 'database',
  },
  {
    id: '22',
    title: 'Обновление документации по API',
    author: 'Мария И.',
    avatarUrl: '/assets/img/person.png',
    progress: 100,
    status: 'inProgress',
    time: '10ч',
    assigned: true,
    product: 'allProducts',
    type: 'documentation',
  },
  {
    id: '23',
    title: 'Анализ производительности и мониторинг сервера',
    author: 'Константин Ф.',
    avatarUrl: '/assets/img/person.png',
    progress: 40,
    status: 'draft',
    time: '22ч',
    assigned: false,
    product: 'option2',
    type: 'analytics',
  },
  {
    id: '24',
    title: 'Проверка на соответствие стандартам безопасности',
    author: 'Алексей Г.',
    avatarUrl: '/assets/img/person.png',
    progress: 100,
    status: 'inProgress',
    time: '7ч',
    assigned: true,
    product: 'option1',
    type: 'security',
  },
  {
    id: '25',
    title: 'Создание резервной копии базы данных',
    author: 'Юлия Л.',
    avatarUrl: '/assets/img/person.png',
    progress: 100,
    status: 'inProgress',
    time: '2ч',
    assigned: true,
    product: 'allProducts',
    type: 'backup',
  },
  {
    id: '26',
    title: 'Анализ логов и выявление причин сбоев',
    author: 'Николай Д.',
    avatarUrl: '/assets/img/person.png',
    progress: 60,
    status: 'inProgress',
    time: '18ч',
    assigned: false,
    product: 'option3',
    type: 'maintenance',
  },
  {
    id: '27',
    title: 'Тестирование отказоустойчивости системы',
    author: 'Ольга А.',
    avatarUrl: '/assets/img/person.png',
    progress: 90,
    status: 'inReview',
    time: '14ч',
    assigned: true,
    product: 'option1',
    type: 'test',
  },
];

export const menuItems: MenuItems[] = [
  {
    name: 'Главная',
    link: '',
    icon: 'rocket',
  },
  {
    name: 'Проекты',
    link: '',
    icon: 'projects',
  },
  { name: 'Команда',
    link: '',
    icon: 'team' },
  {
    name: 'Канбан',
    link: '',
    icon: 'kanban',
  },
  {
    name: 'Итерации',
    link: '',
    icon: 'iteration',
  },
];

export const categories = [
  { name: 'На согласование', status: 'toApproval' },
  { name: 'На ревью', status: 'inReview' },
  { name: 'Для работы', status: 'inProgress' },
  { name: 'Черновики', status: 'draft' },
];

export const filteredOptions1 = [
  { value: 'allProducts', label: 'Все продукты' },
  { value: 'option1', label: 'Название №1' },
  { value: 'option2', label: 'Название №2' },
  { value: 'option3', label: 'Название №3' },
];

export const filteredOptions2 =[
  { value: 'all', label: 'Все задачи' },
  { value: 'common', label: 'Общие' },
  { value: 'development', label: 'Разработка' },
  { value: 'test', label: 'Тестирование' },
  { value: 'errors', label: 'Ошибки' },
];

export const allCards: Card[] = [
  {
    id: '1',
    title: 'Разработка нового компонента для отображения графиков',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 100,
    status: 'done',
    time: '5ч',
    assigned: true,
    product: 'option1',
    type: 'development',
    inProgressCard: true,
  },
  {
    id: '2',
    title: 'Рефакторинг кода модуля авторизации',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 100,
    status: 'done',
    time: '24ч',
    assigned: true,
    product: 'option2',
    type: 'test',
    onPause: true,
  },
  {
    id: '3',
    title: 'Устранить проблемы с кроссбраузерной совместимостью',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 75,
    status: 'inProgress',
    time: '12ч',
    assigned: false,
    product: 'option3',
    type: 'errors',
    onPause: true,
  },
  {
    id: '4',
    title: 'Ошибка валидации формы при пустом поле "номер телефона"',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 50,
    status: 'paused',
    time: '24ч',
    assigned: false,
    product: 'allProducts',
    type: 'common',
    onPause: true,
  },
  {
    id: '5',
    title: 'Рефакторинг кода модуля авторизации',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 100,
    status: 'done',
    time: '24ч',
    assigned: true,
    product: 'option2',
    type: 'test',
    onPause: true,
  },
  {
    id: '6',
    title: 'Устранить проблемы с кроссбраузерной совместимостью',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 75,
    status: 'inProgress',
    time: '12ч',
    assigned: false,
    product: 'option3',
    type: 'errors',
    onPause: true,
  },
  {
    id: '7',
    title: 'Ошибка валидации формы при пустом поле "номер телефона"',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 50,
    status: 'paused',
    time: '24ч',
    assigned: false,
    product: 'allProducts',
    type: 'common',
    onPause: true,
  },
  {
    id: '8',
    title: 'Рефакторинг кода модуля авторизации',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 100,
    status: 'done',
    time: '24ч',
    assigned: true,
    product: 'option2',
    type: 'test',
    onPause: true,
  },
  {
    id: '9',
    title: 'Устранить проблемы с кроссбраузерной совместимостью',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 75,
    status: 'inProgress',
    time: '12ч',
    assigned: false,
    product: 'option3',
    type: 'errors',
    onPause: true,
  },
  {
    id: '10',
    title: 'Ошибка валидации формы при пустом поле "номер телефона"',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 50,
    status: 'paused',
    time: '24ч',
    assigned: false,
    product: 'allProducts',
    type: 'common',
    onPause: true,
  },
  {
    id: '11',
    title: 'Рефакторинг кода модуля авторизации',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 100,
    status: 'done',
    time: '24ч',
    assigned: true,
    product: 'option2',
    type: 'test',
    onPause: true,
  },
  {
    id: '12',
    title: 'Устранить проблемы с кроссбраузерной совместимостью',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 75,
    status: 'inProgress',
    time: '12ч',
    assigned: false,
    product: 'option3',
    type: 'errors',
    onPause: true,
  },
  {
    id: '13',
    title: 'Ошибка валидации формы при пустом поле "номер телефона"',
    author: 'Вильгельмина Ш.',
    avatarUrl: '/assets/img/person.png',
    progress: 50,
    status: 'paused',
    time: '24ч',
    assigned: false,
    product: 'allProducts',
    type: 'common',
    onPause: true,
  },
];
